### ISSUE TITLE
import not working

### ISSUE THREAD

**Issue by pythonms** [laike9m/Cyberbrain#88] opened 2021-02-10 08:15 UTC
`Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
cyberbrain==0.1.1

`
 import cyberbrain
Exception ignored in: <module 'threading' from '/usr/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 1355, in _shutdown
    def _shutdown():
  File "/home/ms/ve/bs2/lib/python3.8/site-packages/cyberbrain/internal/_detect_computed_goto.py", line 9, in global_tracer
    last_i = frame.f_back.f_lasti  # Win: 38, Linux and Mac: 40
AttributeError: 'NoneType' object has no attribute 'f_lasti'
 `

**Comment by laike9m** [comment] 2021-02-10 19:10
Hi, could you paste a snippet that can reproduce this bug?

Though from the error message, it looks like you're using cb with threading, which is [not supported](https://github.com/laike9m/Cyberbrain/blob/master/docs/Features.md#known-limitations) for now.

**Comment by laike9m** [comment] 2021-02-11 17:05
Since I don't get more information, I'll use my best judgement to close this issue, cause it's mostly expected due to the reason mentioned above. But feel free to comment if it's not.

**Comment by joezhouchenye** [comment] 2021-04-13 05:41
python 3.7.0
Cyberbrain 0.1.4
Windows 10
Similar problem in the Terminal, the graph shows up though.
```
Exception ignored in: <async_generator object _ag at 0x000002085F2651E0>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\types.py", line 27, in _ag
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\cyberbrain\internal\_detect_computed_goto.py", line 9, in global_tracer
AttributeError: 'NoneType' object has no attribute 'f_lasti'
```

**Comment by joezhouchenye** [comment] 2021-04-13 05:43
The test code is here.
```python
import struct
import time
from cyberbrain import trace

@trace
def test():
    a = b'\x00\x00'*4096
    start = time.time()
    ans = [0]*(len(a)//2)
    for i in range(0, len(a)//2):
        ans[i] = int.from_bytes(a[(i*2):(i*2+2)], byteorder='little')
    length = len(ans)
    data = struct.pack(str(length)+'H', *ans)
    stop = time.time()
    print(stop-start)

if __name__ == '__main__':
    test()
```

**Comment by laike9m** [comment] 2021-04-18 21:53
Hi @joezhouchenye, I tried to run your code on Python 3.7.9 + Win 10, and can't reproduce this error. Could you try using the latest version of Python 3.7 and see if the error still exists?

**Comment by joezhouchenye** [comment] 2021-04-20 03:02
It seems that there are some setting problems. I freshly installed python3.7.0 and VS Code on another computer and there is no error. I cannot figure out why yet.

**Comment by laike9m** [comment] 2021-04-21 01:08
Sounds good, glad you got it working.

**Closed by laike9m** 2021-04-21 01:08 UTC
Labels: needs more info
